name: AO Network Nonce Monitor - State 2

on:
  schedule:
    - cron: '*/5 * * * *'
  
  workflow_dispatch:

concurrency:
  group: nonce-monitor-state2
  cancel-in-progress: false

jobs:
  monitor-nonce:
    name: Monitor AO Nonce - State 2
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Display workflow info
        run: |
          echo "Workflow: ${{ github.workflow }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run number: ${{ github.run_number }}"
          echo "Triggered by: ${{ github.event_name }}"
          echo "State URL: ${{ secrets.STATE_URL_2 }}"
          echo "Time: $(date -u)"
      
      - name: Run nonce monitor
        env:
          STATE_URL: ${{ secrets.STATE_URL_2 }}
          CONFIG_FILE: ./process-ids.state-2.txt
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          REQUEST_TIMEOUT: ${{ secrets.REQUEST_TIMEOUT || '10000' }}
        run: |
          echo "Starting nonce monitor for State 2..."
          node nonce-monitor.js
          EXIT_CODE=$?
          echo "Monitor completed with exit code: $EXIT_CODE"
          exit $EXIT_CODE
      
      - name: Workflow summary
        if: always()
        run: |
          echo "### Nonce Monitor Results - State 2 :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Status:** ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          echo "**State URL:** ${{ secrets.STATE_URL_2 }}" >> $GITHUB_STEP_SUMMARY
          echo "**Config File:** ./process-ids.state-2.txt" >> $GITHUB_STEP_SUMMARY
          echo "**Time:** $(date -u)" >> $GITHUB_STEP_SUMMARY
          echo "**Run ID:** ${{ github.run_id }}" >> $GITHUB_STEP_SUMMARY
