name: AO Network Nonce Monitor - State 1

on:
  schedule:
    - cron: '*/5 * * * *'
  
  workflow_dispatch:

concurrency:
  group: nonce-monitor-state1
  cancel-in-progress: false

jobs:
  monitor-nonce:
    name: Monitor AO Nonce - State 1
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Display workflow info
        run: |
          echo "Workflow: ${{ github.workflow }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run number: ${{ github.run_number }}"
          echo "Triggered by: ${{ github.event_name }}"
          echo "State URL: ${{ secrets.STATE_URL_1 || 'https://state.forward.computer' }}"
          echo "Time: $(date -u)"
      
       - name: Run nonce monitor
        env:
          STATE_URL: ${{ secrets.STATE_URL_1 || 'https://state.forward.computer' }}
          CONFIG_FILE: ./process-ids.txt
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          REQUEST_TIMEOUT: ${{ secrets.REQUEST_TIMEOUT || '10000' }}
          SU_ROUTER_MAX_RETRIES: ${{ secrets.SU_ROUTER_MAX_RETRIES || '5' }}
          SU_ROUTER_BASE_DELAY: ${{ secrets.SU_ROUTER_BASE_DELAY || '1000' }}
          SU_ROUTER_MAX_DELAY: ${{ secrets.SU_ROUTER_MAX_DELAY || '30000' }}
          PAGERDUTY_ENABLED: true
          PAGERDUTY_ROUTING_KEY: ${{ secrets.PAGERDUTY_ROUTING_KEY }}
          PAGERDUTY_SEVERITY_THRESHOLD: ${{ secrets.PAGERDUTY_SEVERITY_THRESHOLD || '50' }}
          PAGERDUTY_AUTO_RESOLVE: true
        run: |
          echo "Starting nonce monitor for State 1..."
          node nonce-monitor.js
          EXIT_CODE=$?
          echo "Monitor completed with exit code: $EXIT_CODE"
          exit $EXIT_CODE
      
      - name: Workflow summary
        if: always()
        run: |
          echo "### Nonce Monitor Results - State 1 :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Status:** ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          echo "**State URL:** ${{ secrets.STATE_URL_1 || 'https://state.forward.computer' }}" >> $GITHUB_STEP_SUMMARY
          echo "**Config File:** ./process-ids.txt" >> $GITHUB_STEP_SUMMARY
          echo "**Time:** $(date -u)" >> $GITHUB_STEP_SUMMARY
          echo "**Run ID:** ${{ github.run_id }}" >> $GITHUB_STEP_SUMMARY
